version: '3'

services:
  app1:
    image: gameofthree
    ports:
      - "8080:80"
    environment:
      SPRING_APPLICATION_JSON: '{"server.port":80,"applicationName":"app1","http.otherPlayerUrl":"http://app2"}'
  app2:
    image: gameofthree
    ports:
      - "8090:80"
    environment:
      SPRING_APPLICATION_JSON: '{"server.port":80,"applicationName":"app2","http.otherPlayerUrl":"http://app1"}'