version: '3'

services:
  app1:
    image: gameofthree
    ports:
      - "8080:80"
    environment:
      SPRING_APPLICATION_JSON: '{"applicationName":"app1","otherPlayerUrl":"http://app2"}'
  app2:
    image: gameofthree
    ports:
      - "8090:80"
    environment:
      SPRING_APPLICATION_JSON: '{"applicationName":"app2","otherPlayerUrl":"http://app1"}'